from retailcrm.v5.resources.custom_fields import CustomFieldsController
from retailcrm.v5.resources.customers import CustomersController
from retailcrm.v5.resources.loyalty import LoyaltyController
from retailcrm.v5.resources.orders import OrdersController
from retailcrm.v5.resources.payments import PaymentApiResource
from retailcrm.v5.resources.references import ReferencesController
from retailcrm.v5.resources.settings import SettingsApiResource
from retailcrm.v5.resources.store import StoreApiResource
from retailcrm.v5.resources.tasks import TasksApiResource
from retailcrm.v5.resources.users import UsersApiResource
from retailcrm.v5.resources.delivery import DeliveryController
from retailcrm.v5.resources.web_analytics import WebAnalyticsApiResource
from retailcrm.v5.resources.verification import VerificationController
from retailcrm.v5.resources.statistic import StatisticApiResource
from retailcrm.v5.resources.telephony import TelephonyApiResource
from retailcrm.v5.resources.segments import SegmentsApiResource
from retailcrm.v5.resources.orders_packs import OrdersPacksApiResource
from retailcrm.v5.resources.corporate_customers import CorporateCustomersController