from retailcrm.v5.controllers.custom_fields import CustomFieldsController
from retailcrm.v5.controllers.customers import CustomersController
from retailcrm.v5.controllers.loyalty import LoyaltyController
from retailcrm.v5.controllers.orders import OrdersController
from retailcrm.v5.controllers.payments import PaymentController
from retailcrm.v5.controllers.references import ReferencesController
from retailcrm.v5.controllers.store import StoreController
from retailcrm.v5.controllers.tasks import TasksController
from retailcrm.v5.controllers.users import UsersController
from retailcrm.v5.controllers.delivery import DeliveryController
from retailcrm.v5.controllers.web_analytics import WebAnalyticsController
from retailcrm.v5.controllers.verification import VerificationController
from retailcrm.v5.controllers.statistic import StatisticController
from retailcrm.v5.controllers.corporate_customers import CorporateCustomersController